<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['code' => 'AD', 'name_en' => 'Andorra', 'name_de' => 'Andorra'],
            ['code' => 'AE', 'name_en' => 'United Arab Emirates', 'name_de' => 'Vereinigte Arabische Emirate'],
            ['code' => 'AF', 'name_en' => 'Afghanistan', 'name_de' => 'Afghanistan'],
            ['code' => 'AG', 'name_en' => 'Antigua and Barbuda', 'name_de' => 'Antigua und Barbuda'],
            ['code' => 'AI', 'name_en' => 'Anguilla', 'name_de' => 'Anguilla'],
            ['code' => 'AL', 'name_en' => 'Albania', 'name_de' => 'Albanien'],
            ['code' => 'AM', 'name_en' => 'Armenia', 'name_de' => 'Armenien'],
            ['code' => 'AO', 'name_en' => 'Angola', 'name_de' => 'Angola'],
            ['code' => 'AQ', 'name_en' => 'Antarctica', 'name_de' => 'Antarktis'],
            ['code' => 'AR', 'name_en' => 'Argentina', 'name_de' => 'Argentinien'],
            ['code' => 'AS', 'name_en' => 'American Samoa', 'name_de' => 'Amerikanisch-Samoa'],
            ['code' => 'AT', 'name_en' => 'Austria', 'name_de' => 'Österreich'],
            ['code' => 'AU', 'name_en' => 'Australia', 'name_de' => 'Australien'],
            ['code' => 'AW', 'name_en' => 'Aruba', 'name_de' => 'Aruba'],
            ['code' => 'AX', 'name_en' => 'Åland Islands', 'name_de' => 'Ålandinseln'],
            ['code' => 'AZ', 'name_en' => 'Azerbaijan', 'name_de' => 'Aserbaidschan'],
            ['code' => 'BA', 'name_en' => 'Bosnia and Herzegovina', 'name_de' => 'Bosnien und Herzegowina'],
            ['code' => 'BB', 'name_en' => 'Barbados', 'name_de' => 'Barbados'],
            ['code' => 'BD', 'name_en' => 'Bangladesh', 'name_de' => 'Bangladesch'],
            ['code' => 'BE', 'name_en' => 'Belgium', 'name_de' => 'Belgien'],
            ['code' => 'BF', 'name_en' => 'Burkina Faso', 'name_de' => 'Burkina Faso'],
            ['code' => 'BG', 'name_en' => 'Bulgaria', 'name_de' => 'Bulgarien'],
            ['code' => 'BH', 'name_en' => 'Bahrain', 'name_de' => 'Bahrain'],
            ['code' => 'BI', 'name_en' => 'Burundi', 'name_de' => 'Burundi'],
            ['code' => 'BJ', 'name_en' => 'Benin', 'name_de' => 'Benin'],
            ['code' => 'BL', 'name_en' => 'Saint Barthélemy', 'name_de' => 'Saint-Barthélemy'],
            ['code' => 'BM', 'name_en' => 'Bermuda', 'name_de' => 'Bermuda'],
            ['code' => 'BN', 'name_en' => 'Brunei Darussalam', 'name_de' => 'Brunei'],
            ['code' => 'BO', 'name_en' => 'Bolivia, Plurinational State of', 'name_de' => 'Bolivien'],
            ['code' => 'BQ', 'name_en' => 'Bonaire, Sint Eustatius and Saba', 'name_de' => 'Bonaire, Sint Eustatius und Saba'],
            ['code' => 'BR', 'name_en' => 'Brazil', 'name_de' => 'Brasilien'],
            ['code' => 'BS', 'name_en' => 'Bahamas', 'name_de' => 'Bahamas'],
            ['code' => 'BT', 'name_en' => 'Bhutan', 'name_de' => 'Bhutan'],
            ['code' => 'BV', 'name_en' => 'Bouvet Island', 'name_de' => 'Bouvetinsel'],
            ['code' => 'BW', 'name_en' => 'Botswana', 'name_de' => 'Botswana'],
            ['code' => 'BY', 'name_en' => 'Belarus', 'name_de' => 'Belarus'],
            ['code' => 'BZ', 'name_en' => 'Belize', 'name_de' => 'Belize'],
            ['code' => 'CA', 'name_en' => 'Canada', 'name_de' => 'Kanada'],
            ['code' => 'CC', 'name_en' => 'Cocos (Keeling) Islands', 'name_de' => 'Kokosinseln'],
            ['code' => 'CD', 'name_en' => 'Congo, Democratic Republic of the', 'name_de' => 'Kongo, Demokratische Republik'],
            ['code' => 'CF', 'name_en' => 'Central African Republic', 'name_de' => 'Zentralafrikanische Republik'],
            ['code' => 'CG', 'name_en' => 'Congo', 'name_de' => 'Kongo, Republik'],
            ['code' => 'CH', 'name_en' => 'Switzerland', 'name_de' => 'Schweiz'],
            ['code' => 'CI', 'name_en' => 'Côte d\'Ivoire', 'name_de' => 'Elfenbeinküste'],
            ['code' => 'CK', 'name_en' => 'Cook Islands', 'name_de' => 'Cookinseln'],
            ['code' => 'CL', 'name_en' => 'Chile', 'name_de' => 'Chile'],
            ['code' => 'CM', 'name_en' => 'Cameroon', 'name_de' => 'Kamerun'],
            ['code' => 'CN', 'name_en' => 'China', 'name_de' => 'China'],
            ['code' => 'CO', 'name_en' => 'Colombia', 'name_de' => 'Kolumbien'],
            ['code' => 'CR', 'name_en' => 'Costa Rica', 'name_de' => 'Costa Rica'],
            ['code' => 'CU', 'name_en' => 'Cuba', 'name_de' => 'Kuba'],
            ['code' => 'CV', 'name_en' => 'Cabo Verde', 'name_de' => 'Kap Verde'],
            ['code' => 'CW', 'name_en' => 'Curaçao', 'name_de' => 'Curaçao'],
            ['code' => 'CX', 'name_en' => 'Christmas Island', 'name_de' => 'Weihnachtsinsel'],
            ['code' => 'CY', 'name_en' => 'Cyprus', 'name_de' => 'Zypern'],
            ['code' => 'CZ', 'name_en' => 'Czechia', 'name_de' => 'Tschechien'],
            ['code' => 'DE', 'name_en' => 'Germany', 'name_de' => 'Deutschland'],
            ['code' => 'DJ', 'name_en' => 'Djibouti', 'name_de' => 'Dschibuti'],
            ['code' => 'DK', 'name_en' => 'Denmark', 'name_de' => 'Dänemark'],
            ['code' => 'DM', 'name_en' => 'Dominica', 'name_de' => 'Dominica'],
            ['code' => 'DO', 'name_en' => 'Dominican Republic', 'name_de' => 'Dominikanische Republik'],
            ['code' => 'DZ', 'name_en' => 'Algeria', 'name_de' => 'Algerien'],
            ['code' => 'EC', 'name_en' => 'Ecuador', 'name_de' => 'Ecuador'],
            ['code' => 'EE', 'name_en' => 'Estonia', 'name_de' => 'Estland'],
            ['code' => 'EG', 'name_en' => 'Egypt', 'name_de' => 'Ägypten'],
            ['code' => 'EH', 'name_en' => 'Western Sahara', 'name_de' => 'Westsahara'],
            ['code' => 'ER', 'name_en' => 'Eritrea', 'name_de' => 'Eritrea'],
            ['code' => 'ES', 'name_en' => 'Spain', 'name_de' => 'Spanien'],
            ['code' => 'ET', 'name_en' => 'Ethiopia', 'name_de' => 'Äthiopien'],
            ['code' => 'FI', 'name_en' => 'Finland', 'name_de' => 'Finnland'],
            ['code' => 'FJ', 'name_en' => 'Fiji', 'name_de' => 'Fidschi'],
            ['code' => 'FK', 'name_en' => 'Falkland Islands (Malvinas)', 'name_de' => 'Falklandinseln'],
            ['code' => 'FM', 'name_en' => 'Micronesia, Federated States of', 'name_de' => 'Mikronesien'],
            ['code' => 'FO', 'name_en' => 'Faroe Islands', 'name_de' => 'Färöer'],
            ['code' => 'FR', 'name_en' => 'France', 'name_de' => 'Frankreich'],
            ['code' => 'GA', 'name_en' => 'Gabon', 'name_de' => 'Gabun'],
            ['code' => 'GB', 'name_en' => 'United Kingdom of Great Britain and Northern Ireland', 'name_de' => 'Vereinigtes Königreich'],
            ['code' => 'GD', 'name_en' => 'Grenada', 'name_de' => 'Grenada'],
            ['code' => 'GE', 'name_en' => 'Georgia', 'name_de' => 'Georgien'],
            ['code' => 'GF', 'name_en' => 'French Guiana', 'name_de' => 'Französisch-Guayana'],
            ['code' => 'GG', 'name_en' => 'Guernsey', 'name_de' => 'Guernsey'],
            ['code' => 'GH', 'name_en' => 'Ghana', 'name_de' => 'Ghana'],
            ['code' => 'GI', 'name_en' => 'Gibraltar', 'name_de' => 'Gibraltar'],
            ['code' => 'GL', 'name_en' => 'Greenland', 'name_de' => 'Grönland'],
            ['code' => 'GM', 'name_en' => 'Gambia', 'name_de' => 'Gambia'],
            ['code' => 'GN', 'name_en' => 'Guinea', 'name_de' => 'Guinea'],
            ['code' => 'GP', 'name_en' => 'Guadeloupe', 'name_de' => 'Guadeloupe'],
            ['code' => 'GQ', 'name_en' => 'Equatorial Guinea', 'name_de' => 'Äquatorialguinea'],
            ['code' => 'GR', 'name_en' => 'Greece', 'name_de' => 'Griechenland'],
            ['code' => 'GS', 'name_en' => 'South Georgia and the South Sandwich Islands', 'name_de' => 'Südgeorgien und die Südlichen Sandwichinseln'],
            ['code' => 'GT', 'name_en' => 'Guatemala', 'name_de' => 'Guatemala'],
            ['code' => 'GU', 'name_en' => 'Guam', 'name_de' => 'Guam'],
            ['code' => 'GW', 'name_en' => 'Guinea-Bissau', 'name_de' => 'Guinea-Bissau'],
            ['code' => 'GY', 'name_en' => 'Guyana', 'name_de' => 'Guyana'],
            ['code' => 'HK', 'name_en' => 'Hong Kong', 'name_de' => 'Hongkong'],
            ['code' => 'HM', 'name_en' => 'Heard Island and McDonald Islands', 'name_de' => 'Heard und McDonaldinseln'],
            ['code' => 'HN', 'name_en' => 'Honduras', 'name_de' => 'Honduras'],
            ['code' => 'HR', 'name_en' => 'Croatia', 'name_de' => 'Kroatien'],
            ['code' => 'HT', 'name_en' => 'Haiti', 'name_de' => 'Haiti'],
            ['code' => 'HU', 'name_en' => 'Hungary', 'name_de' => 'Ungarn'],
            ['code' => 'ID', 'name_en' => 'Indonesia', 'name_de' => 'Indonesien'],
            ['code' => 'IE', 'name_en' => 'Ireland', 'name_de' => 'Irland'],
            ['code' => 'IL', 'name_en' => 'Israel', 'name_de' => 'Israel'],
            ['code' => 'IM', 'name_en' => 'Isle of Man', 'name_de' => 'Isle of Man'],
            ['code' => 'IN', 'name_en' => 'India', 'name_de' => 'Indien'],
            ['code' => 'IO', 'name_en' => 'British Indian Ocean Territory', 'name_de' => 'Britisches Territorium im Indischen Ozean'],
            ['code' => 'IQ', 'name_en' => 'Iraq', 'name_de' => 'Irak'],
            ['code' => 'IR', 'name_en' => 'Iran, Islamic Republic of', 'name_de' => 'Iran'],
            ['code' => 'IS', 'name_en' => 'Iceland', 'name_de' => 'Island'],
            ['code' => 'IT', 'name_en' => 'Italy', 'name_de' => 'Italien'],
            ['code' => 'JE', 'name_en' => 'Jersey', 'name_de' => 'Jersey'],
            ['code' => 'JM', 'name_en' => 'Jamaica', 'name_de' => 'Jamaika'],
            ['code' => 'JO', 'name_en' => 'Jordan', 'name_de' => 'Jordanien'],
            ['code' => 'JP', 'name_en' => 'Japan', 'name_de' => 'Japan'],
            ['code' => 'KE', 'name_en' => 'Kenya', 'name_de' => 'Kenia'],
            ['code' => 'KG', 'name_en' => 'Kyrgyzstan', 'name_de' => 'Kirgisistan'],
            ['code' => 'KH', 'name_en' => 'Cambodia', 'name_de' => 'Kambodscha'],
            ['code' => 'KI', 'name_en' => 'Kiribati', 'name_de' => 'Kiribati'],
            ['code' => 'KM', 'name_en' => 'Comoros', 'name_de' => 'Komoren'],
            ['code' => 'KN', 'name_en' => 'Saint Kitts and Nevis', 'name_de' => 'St. Kitts und Nevis'],
            ['code' => 'KP', 'name_en' => 'Korea, Democratic People\'s Republic of', 'name_de' => 'Nordkorea'],
            ['code' => 'KR', 'name_en' => 'Korea, Republic of', 'name_de' => 'Südkorea'],
            ['code' => 'KW', 'name_en' => 'Kuwait', 'name_de' => 'Kuwait'],
            ['code' => 'KY', 'name_en' => 'Cayman Islands', 'name_de' => 'Kaimaninseln'],
            ['code' => 'KZ', 'name_en' => 'Kazakhstan', 'name_de' => 'Kasachstan'],
            ['code' => 'LA', 'name_en' => 'Lao People\'s Democratic Republic', 'name_de' => 'Laos'],
            ['code' => 'LB', 'name_en' => 'Lebanon', 'name_de' => 'Libanon'],
            ['code' => 'LC', 'name_en' => 'Saint Lucia', 'name_de' => 'St. Lucia'],
            ['code' => 'LI', 'name_en' => 'Liechtenstein', 'name_de' => 'Liechtenstein'],
            ['code' => 'LK', 'name_en' => 'Sri Lanka', 'name_de' => 'Sri Lanka'],
            ['code' => 'LR', 'name_en' => 'Liberia', 'name_de' => 'Liberia'],
            ['code' => 'LS', 'name_en' => 'Lesotho', 'name_de' => 'Lesotho'],
            ['code' => 'LT', 'name_en' => 'Lithuania', 'name_de' => 'Litauen'],
            ['code' => 'LU', 'name_en' => 'Luxembourg', 'name_de' => 'Luxemburg'],
            ['code' => 'LV', 'name_en' => 'Latvia', 'name_de' => 'Lettland'],
            ['code' => 'LY', 'name_en' => 'Libya', 'name_de' => 'Libyen'],
            ['code' => 'MA', 'name_en' => 'Morocco', 'name_de' => 'Marokko'],
            ['code' => 'MC', 'name_en' => 'Monaco', 'name_de' => 'Monaco'],
            ['code' => 'MD', 'name_en' => 'Moldova, Republic of', 'name_de' => 'Moldau'],
            ['code' => 'ME', 'name_en' => 'Montenegro', 'name_de' => 'Montenegro'],
            ['code' => 'MF', 'name_en' => 'Saint Martin (French part)', 'name_de' => 'Saint-Martin'],
            ['code' => 'MG', 'name_en' => 'Madagascar', 'name_de' => 'Madagaskar'],
            ['code' => 'MH', 'name_en' => 'Marshall Islands', 'name_de' => 'Marshallinseln'],
            ['code' => 'MK', 'name_en' => 'North Macedonia', 'name_de' => 'Nordmazedonien'],
            ['code' => 'ML', 'name_en' => 'Mali', 'name_de' => 'Mali'],
            ['code' => 'MM', 'name_en' => 'Myanmar', 'name_de' => 'Myanmar'],
            ['code' => 'MN', 'name_en' => 'Mongolia', 'name_de' => 'Mongolei'],
            ['code' => 'MO', 'name_en' => 'Macao', 'name_de' => 'Macau'],
            ['code' => 'MP', 'name_en' => 'Northern Mariana Islands', 'name_de' => 'Nördliche Marianen'],
            ['code' => 'MQ', 'name_en' => 'Martinique', 'name_de' => 'Martinique'],
            ['code' => 'MR', 'name_en' => 'Mauritania', 'name_de' => 'Mauretanien'],
            ['code' => 'MS', 'name_en' => 'Montserrat', 'name_de' => 'Montserrat'],
            ['code' => 'MT', 'name_en' => 'Malta', 'name_de' => 'Malta'],
            ['code' => 'MU', 'name_en' => 'Mauritius', 'name_de' => 'Mauritius'],
            ['code' => 'MV', 'name_en' => 'Maldives', 'name_de' => 'Malediven'],
            ['code' => 'MW', 'name_en' => 'Malawi', 'name_de' => 'Malawi'],
            ['code' => 'MX', 'name_en' => 'Mexico', 'name_de' => 'Mexiko'],
            ['code' => 'MY', 'name_en' => 'Malaysia', 'name_de' => 'Malaysia'],
            ['code' => 'MZ', 'name_en' => 'Mozambique', 'name_de' => 'Mosambik'],
            ['code' => 'NA', 'name_en' => 'Namibia', 'name_de' => 'Namibia'],
            ['code' => 'NC', 'name_en' => 'New Caledonia', 'name_de' => 'Neukaledonien'],
            ['code' => 'NE', 'name_en' => 'Niger', 'name_de' => 'Niger'],
            ['code' => 'NF', 'name_en' => 'Norfolk Island', 'name_de' => 'Norfolkinsel'],
            ['code' => 'NG', 'name_en' => 'Nigeria', 'name_de' => 'Nigeria'],
            ['code' => 'NI', 'name_en' => 'Nicaragua', 'name_de' => 'Nicaragua'],
            ['code' => 'NL', 'name_en' => 'Netherlands', 'name_de' => 'Niederlande'],
            ['code' => 'NO', 'name_en' => 'Norway', 'name_de' => 'Norwegen'],
            ['code' => 'NP', 'name_en' => 'Nepal', 'name_de' => 'Nepal'],
            ['code' => 'NR', 'name_en' => 'Nauru', 'name_de' => 'Nauru'],
            ['code' => 'NU', 'name_en' => 'Niue', 'name_de' => 'Niue'],
            ['code' => 'NZ', 'name_en' => 'New Zealand', 'name_de' => 'Neuseeland'],
            ['code' => 'OM', 'name_en' => 'Oman', 'name_de' => 'Oman'],
            ['code' => 'PA', 'name_en' => 'Panama', 'name_de' => 'Panama'],
            ['code' => 'PE', 'name_en' => 'Peru', 'name_de' => 'Peru'],
            ['code' => 'PF', 'name_en' => 'French Polynesia', 'name_de' => 'Französisch-Polynesien'],
            ['code' => 'PG', 'name_en' => 'Papua New Guinea', 'name_de' => 'Papua-Neuguinea'],
            ['code' => 'PH', 'name_en' => 'Philippines', 'name_de' => 'Philippinen'],
            ['code' => 'PK', 'name_en' => 'Pakistan', 'name_de' => 'Pakistan'],
            ['code' => 'PL', 'name_en' => 'Poland', 'name_de' => 'Polen'],
            ['code' => 'PM', 'name_en' => 'Saint Pierre and Miquelon', 'name_de' => 'Saint-Pierre und Miquelon'],
            ['code' => 'PN', 'name_en' => 'Pitcairn', 'name_de' => 'Pitcairninseln'],
            ['code' => 'PR', 'name_en' => 'Puerto Rico', 'name_de' => 'Puerto Rico'],
            ['code' => 'PS', 'name_en' => 'Palestine, State of', 'name_de' => 'Palästina'],
            ['code' => 'PT', 'name_en' => 'Portugal', 'name_de' => 'Portugal'],
            ['code' => 'PW', 'name_en' => 'Palau', 'name_de' => 'Palau'],
            ['code' => 'PY', 'name_en' => 'Paraguay', 'name_de' => 'Paraguay'],
            ['code' => 'QA', 'name_en' => 'Qatar', 'name_de' => 'Katar'],
            ['code' => 'RE', 'name_en' => 'Réunion', 'name_de' => 'Réunion'],
            ['code' => 'RO', 'name_en' => 'Romania', 'name_de' => 'Rumänien'],
            ['code' => 'RS', 'name_en' => 'Serbia', 'name_de' => 'Serbien'],
            ['code' => 'RU', 'name_en' => 'Russian Federation', 'name_de' => 'Russland'],
            ['code' => 'RW', 'name_en' => 'Rwanda', 'name_de' => 'Ruanda'],
            ['code' => 'SA', 'name_en' => 'Saudi Arabia', 'name_de' => 'Saudi-Arabien'],
            ['code' => 'SB', 'name_en' => 'Solomon Islands', 'name_de' => 'Salomonen'],
            ['code' => 'SC', 'name_en' => 'Seychelles', 'name_de' => 'Seychellen'],
            ['code' => 'SD', 'name_en' => 'Sudan', 'name_de' => 'Sudan'],
            ['code' => 'SE', 'name_en' => 'Sweden', 'name_de' => 'Schweden'],
            ['code' => 'SG', 'name_en' => 'Singapore', 'name_de' => 'Singapur'],
            ['code' => 'SH', 'name_en' => 'Saint Helena, Ascension and Tristan da Cunha', 'name_de' => 'St. Helena, Ascension und Tristan da Cunha'],
            ['code' => 'SI', 'name_en' => 'Slovenia', 'name_de' => 'Slowenien'],
            ['code' => 'SJ', 'name_en' => 'Svalbard and Jan Mayen', 'name_de' => 'Svalbard und Jan Mayen'],
            ['code' => 'SK', 'name_en' => 'Slovakia', 'name_de' => 'Slowakei'],
            ['code' => 'SL', 'name_en' => 'Sierra Leone', 'name_de' => 'Sierra Leone'],
            ['code' => 'SM', 'name_en' => 'San Marino', 'name_de' => 'San Marino'],
            ['code' => 'SN', 'name_en' => 'Senegal', 'name_de' => 'Senegal'],
            ['code' => 'SO', 'name_en' => 'Somalia', 'name_de' => 'Somalia'],
            ['code' => 'SR', 'name_en' => 'Suriname', 'name_de' => 'Suriname'],
            ['code' => 'SS', 'name_en' => 'South Sudan', 'name_de' => 'Südsudan'],
            ['code' => 'ST', 'name_en' => 'Sao Tome and Principe', 'name_de' => 'São Tomé und Príncipe'],
            ['code' => 'SV', 'name_en' => 'El Salvador', 'name_de' => 'El Salvador'],
            ['code' => 'SX', 'name_en' => 'Sint Maarten (Dutch part)', 'name_de' => 'Sint Maarten'],
            ['code' => 'SY', 'name_en' => 'Syrian Arab Republic', 'name_de' => 'Syrien'],
            ['code' => 'SZ', 'name_en' => 'Eswatini', 'name_de' => 'Eswatini'],
            ['code' => 'TC', 'name_en' => 'Turks and Caicos Islands', 'name_de' => 'Turks- und Caicosinseln'],
            ['code' => 'TD', 'name_en' => 'Chad', 'name_de' => 'Tschad'],
            ['code' => 'TF', 'name_en' => 'French Southern Territories', 'name_de' => 'Französische Süd- und Antarktisgebiete'],
            ['code' => 'TG', 'name_en' => 'Togo', 'name_de' => 'Togo'],
            ['code' => 'TH', 'name_en' => 'Thailand', 'name_de' => 'Thailand'],
            ['code' => 'TJ', 'name_en' => 'Tajikistan', 'name_de' => 'Tadschikistan'],
            ['code' => 'TK', 'name_en' => 'Tokelau', 'name_de' => 'Tokelau'],
            ['code' => 'TL', 'name_en' => 'Timor-Leste', 'name_de' => 'Timor-Leste'],
            ['code' => 'TM', 'name_en' => 'Turkmenistan', 'name_de' => 'Turkmenistan'],
            ['code' => 'TN', 'name_en' => 'Tunisia', 'name_de' => 'Tunesien'],
            ['code' => 'TO', 'name_en' => 'Tonga', 'name_de' => 'Tonga'],
            ['code' => 'TR', 'name_en' => 'Turkey', 'name_de' => 'Türkei'],
            ['code' => 'TT', 'name_en' => 'Trinidad and Tobago', 'name_de' => 'Trinidad und Tobago'],
            ['code' => 'TV', 'name_en' => 'Tuvalu', 'name_de' => 'Tuvalu'],
            ['code' => 'TW', 'name_en' => 'Taiwan, Province of China', 'name_de' => 'Taiwan'],
            ['code' => 'TZ', 'name_en' => 'Tanzania, United Republic of', 'name_de' => 'Tansania'],
            ['code' => 'UA', 'name_en' => 'Ukraine', 'name_de' => 'Ukraine'],
            ['code' => 'UG', 'name_en' => 'Uganda', 'name_de' => 'Uganda'],
            ['code' => 'UM', 'name_en' => 'United States Minor Outlying Islands', 'name_de' => 'Kleinere Inselbesitzungen der Vereinigten Staaten'],
            ['code' => 'US', 'name_en' => 'United States of America', 'name_de' => 'Vereinigte Staaten'],
            ['code' => 'UY', 'name_en' => 'Uruguay', 'name_de' => 'Uruguay'],
            ['code' => 'UZ', 'name_en' => 'Uzbekistan', 'name_de' => 'Usbekistan'],
            ['code' => 'VA', 'name_en' => 'Holy See', 'name_de' => 'Vatikanstadt'],
            ['code' => 'VC', 'name_en' => 'Saint Vincent and the Grenadines', 'name_de' => 'St. Vincent und die Grenadinen'],
            ['code' => 'VE', 'name_en' => 'Venezuela, Bolivarian Republic of', 'name_de' => 'Venezuela'],
            ['code' => 'VG', 'name_en' => 'Virgin Islands, British', 'name_de' => 'Britische Jungferninseln'],
            ['code' => 'VI', 'name_en' => 'Virgin Islands, U.S.', 'name_de' => 'Amerikanische Jungferninseln'],
            ['code' => 'VN', 'name_en' => 'Viet Nam', 'name_de' => 'Vietnam'],
            ['code' => 'VU', 'name_en' => 'Vanuatu', 'name_de' => 'Vanuatu'],
            ['code' => 'WF', 'name_en' => 'Wallis and Futuna', 'name_de' => 'Wallis und Futuna'],
            ['code' => 'WS', 'name_en' => 'Samoa', 'name_de' => 'Samoa'],
            ['code' => 'YE', 'name_en' => 'Yemen', 'name_de' => 'Jemen'],
            ['code' => 'YT', 'name_en' => 'Mayotte', 'name_de' => 'Mayotte'],
            ['code' => 'ZA', 'name_en' => 'South Africa', 'name_de' => 'Südafrika'],
            ['code' => 'ZM', 'name_en' => 'Zambia', 'name_de' => 'Sambia'],
            ['code' => 'ZW', 'name_en' => 'Zimbabwe', 'name_de' => 'Simbabwe'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
